[project]
name = "tomlkit"
version = "0.13.2"
description = "Style preserving TOML library"
authors = [
    { name = "Sébastien Eustace", email = "sebastien@eustace.io" },
    { name = "Frost Ming", email = "me@frostming.com" },
]
requires-python = ">=3.8"
readme = "README.md"
license = "MIT"

[project.urls]
Homepage = "https://github.com/sdispater/tomlkit"
Repository = "https://github.com/sdispater/tomlkit"

[dependency-groups]
dev = [
    "pytest>=7.2.0,<8",
    "pytest-cov>=4.0.0,<5",
    "PyYAML~=6.0",
    "pre-commit>=2.20.0,<3",
    "mypy>=0.990,<0.991",
    "Sphinx>=4.3.2,<5",
    "furo>=2022.9.29,<2023",
]

[tool.hatch.build.targets.sdist]
include = [
    "tomlkit/py.typed",
    "tests",
    "docs",
    "CHANGELOG.md",
]

[tool.hatch.build.targets.wheel]
include = ["tomlkit/py.typed"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
extend-select = [
  "I",    # isort
  "B",    # flake8-bugbear
  "C4",   # flake8-comprehensions
  "PGH",  # pygrep-hooks
  "RUF",  # ruff
  "W",    # pycodestyle
  "YTT",  # flake8-2020
]
extend-ignore = ["B018", "B019", "RUF018"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["tomlkit"]
known-third-party = ["pytest"]
force-single-line = true
lines-after-imports = 2
lines-between-types = 1
